services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: coude_blog_app
        working_dir: /var/www/html
        volumes:
            - ./src:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        command: sh -c "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8000"
    postgres:
        image: postgres:latest
        container_name: laravel_postgres
        restart: always
        environment:
            POSTGRES_DB: coude_blog
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: 2005
        ports:
            - "5432:5432"
        volumes:
            - pdgata:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: laravel_pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_USER: admin
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        volumes:
            - pgadmin_data:/var/lib/pgadmin
volumes:
    pdgata:
    pgadmin_data:
